services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - './:/frontend'
    env_file:
      - .env.development

