version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - './:/frontend'
    env_file:
      - .env.development

  nginx:
    build:
      context: .
      dockerfile: local_nginx.Dockerfile
    ports:
      - "82:80"
    depends_on:
      - node
